#!/usr/bin/env ruby

$LOAD_PATH.unshift File.dirname(__FILE__) + "/lib"
require 'gamefic'
require 'gamefic/engine/cgi'
include Gamefic

begin
  plot = Plot.new
  file = "#{ARGV[0]}/main.rb"
  plot.load file
  if ARGV[1] != "new"
    savename = ARGV[1]
  else
    savename = ARGV[2]
  end
  engine = Cgi::Engine.new plot, :session_file => savename
  engine.begin_session
  json = engine.run
  engine.end_session
  if engine.user.character.state.kind_of?(CharacterState::Concluded)
    File.delete savename
  end
  puts json
rescue Exception => e
  response = Hash.new
  response[:error] = e.message
  response[:backtrace] = e.backtrace
  puts JSON.generate(response)
end
