#!/usr/bin/env ruby

require "core/game.rb"

if ARGV[0] == nil
	puts "Game file required."
	exit
end

module Gamefic
	story = Story.new
	story.script(ARGV[0])
	player = Player.new
	player.name = "joejoe"
	performance = Performance.new(story)
	performance.introduce player
end
