#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.expand_path(File.dirname(__FILE__)) + "/lib")
require "gamefic"
require "gamefic/entity_ext"
require "gamefic/action_ext"
include Gamefic

Story.instance.require_script "#{ARGV[0]}"
engine = Engine.new
engine.run
