#!/usr/bin/env ruby

# Use the local lib instead of the gem for testing and debugging
$LOAD_PATH.unshift File.dirname(__FILE__) + "/lib"

require "gamefic"
require "gamefic/base"
include Gamefic

story = Story.new
story.require_script "#{ARGV[0]}"
engine = Engine.new story
engine.run
