#!/usr/bin/env ruby

require "lib/game"

story = Gamefic::Story.new
story.load ARGV[0]

if ARGV[1] == 'tick'
	require "lib/games/singletick"
	game = Gamefic::SingleTick.new story
	game.enroll Gamefic::SingleTick::User.new
else
	require "lib/games/singleturn"
	game = Gamefic::SingleTurn.new story
	game.enroll Gamefic::SingleTurn::User.new
end

game.run
