title: Cloak of Darkness
author: Peter Orme

script_path: ./scripts
import_path: ./imports
media_path: ./media

build_path: ./build
release_path: ./release

targets:
  web:
    platform: Web
    html: ./html
  gfic:
    platform: Gfic
    filename: game.gfic
