# frozen_string_literal: true

require 'gamefic/query/base'
require 'gamefic/query/text'
require 'gamefic/query/result'
require 'gamefic/query/subqueries'
require 'gamefic/query/global'
require 'gamefic/query/abstract'
require 'gamefic/query/children'
require 'gamefic/query/myself'
require 'gamefic/query/descendants'
require 'gamefic/query/ascendants'
require 'gamefic/query/parent'
require 'gamefic/query/siblings'
require 'gamefic/query/family'
