title: Professor
author: Fred Snyder

script_path: ./scripts
import_path: ./imports
media_path: ./media

build_path: ./build
release_path: ./release

libraries:
- standard

targets:
  web:
    platform: Web
  gfic:
    platform: Gfic
    filename: game.gfic
