require 'standard/queries/reachable'
require 'standard/queries/room'
require 'standard/queries/visible'
require 'standard/queries/many_visible'
require 'standard/queries/ambiguous_visible'
require 'standard/queries/plural_visible'
require 'standard/queries/any_expression'
require 'standard/queries/not_expression'